import numpy as np
from mean_var_std import calculate

def test_calculate():
    try:
        assert calculate([2,6,2,8,4,0,1,5,7]) == {
            'mean': [[3.6666666666666665, 5.0, 3.0], [3.3333333333333335, 4.0, 4.333333333333333], 3.888888888888889],
            'variance': [[9.555555555555555, 0.6666666666666666, 13.555555555555555], [4.222222222222222, 10.666666666666666, 6.222222222222222], 8.54320987654321],
            'standard deviation': [[3.091206165165235, 0.816496580927726, 3.6817870057290873], [2.0548046676563256, 3.265986323710904, 2.494438257849294], 2.922717940288885],
            'max': [[8, 6, 7], [6, 8, 7], 8],
            'min': [[1, 4, 0], [2, 0, 1], 0],
            'sum': [[11, 15, 9], [10, 12, 13], 35]
        }
        assert calculate([0,1,2,3,4,5,6,7,8]) == {
            'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
            'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667],
            'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611],
            'max': [[6, 7, 8], [2, 5, 8], 8],
            'min': [[0, 1, 2], [0, 3, 6], 0],
            'sum': [[9, 12, 15], [3, 12, 21], 36]
        }
        print("✅ All tests passed!")
    except AssertionError:
        print("❌ Test failed.")
